# 0 Sample Data Generation

In this notebook we generate sample data for each state of both the trip and weather (and merged) datasets for an easier and faster exemplary compliation of our notebooks. Please keep in mind that we sample the data randomly, therefore the sampled data is solely an exemplary (not perfect) representation of our datasets and some patterns etc. are not represented in the sampled datasets.

For the sampling we decided to sample the datasets down to a total of approx. 10.000 - 15.000 rows, keeping all columns.

All of our data can be found in the following sciebo folder: https://uni-koeln.sciebo.de/s/z5xgdGosd9y9c4e (Password: AAA2026)

In [1]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Import packages                         #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

import pandas as pd

# reset working dir
import os
from pathlib import Path

In [2]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Reset working directory                 #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

def find_project_root():
    for parent in [Path(os.getcwd()), *Path(os.getcwd()).parents]:
        if (parent / "pyproject.toml").exists():
            return parent
    raise FileNotFoundError("Could not find pyproject.toml")

os.chdir(find_project_root())
print(f"Working directory: {os.getcwd()}")

Working directory: /Users/anthony/Documents/Dokumente – MacBook Pro von Anthony/UNI/AAA/AAA_TA_2026

In [11]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Configurations                          #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

SAMPLE_FRAC = 0.002
random_seed = 42

## 0.1 Raw Chicago Trip Data

First we sample the **raw** trip data downloaded from the webportal of the city of chicago: https://data.cityofchicago.org/Transportation/Taxi-Trips-2024-/ajtu-isnz/about_data (downloaded on 05.05.2026).

The trip data fetching can be found here: [Raw Chicago Trip Data](01_Preprocessing/01_01_Fetch_Trip_Data.ipynb)

In [3]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Load raw trip data                      #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

raw_trip_data = pd.read_csv("data/trips/CHICAGO_TAXI_TRIPS_2025.csv")
raw_trip_data.head()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_census_tract,dropoff_census_tract,pickup_community_area,dropoff_community_area,...,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location
0,0275e2d8147a31e1ce320c5fb15f9910563cafe1,84957c8960b674346784746bbc1d48cafff4976b162323...,2025-01-01T00:00:00.000,2025-01-01T00:15:00.000,758.0,2.93,NaN,NaN,8.0,8.0,...,0.0,9.75,Prcard,Flash Cab,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),41.899602,-87.633308,POINT (-87.6333080367 41.899602111)
1,05aa05bf6f3ec476715fad9f706bd137e08e00b7,0cbf5c0f6aca3628d77c7b6fe89715757ed402a70b0f8b...,2025-01-01T00:00:00.000,2025-01-01T00:15:00.000,1233.0,13.66,NaN,NaN,76.0,6.0,...,5.0,48.60,Credit Card,Globe Taxi,41.980264,-87.913625,POINT (-87.913624596 41.9802643146),41.944227,-87.655998,POINT (-87.6559981815 41.9442266014)
2,060f692c4ca69e552c07a97c99715ad51112470e,e533bfdc483206f9c02c1c879a118d88f0a3ca1cd2703f...,2025-01-01T00:00:00.000,2025-01-01T00:00:00.000,6.0,0.00,NaN,NaN,6.0,6.0,...,0.0,30.50,Credit Card,Flash Cab,41.944227,-87.655998,POINT (-87.6559981815 41.9442266014),41.944227,-87.655998,POINT (-87.6559981815 41.9442266014)
3,0b2d1368456148b049af41dc8aa565d688081756,2d5029b701200a2ab66bd5071f743efe20a3036597d2b3...,2025-01-01T00:00:00.000,2025-01-01T00:00:00.000,11.0,0.00,NaN,NaN,77.0,77.0,...,0.0,25.62,Credit Card,Sun Taxi,41.986712,-87.663416,POINT (-87.6634164054 41.9867117999),41.986712,-87.663416,POINT (-87.6634164054 41.9867117999)
4,17365c83264f028a307ac70308d770fe03bcbcae,c3f8e0b6712bf3ea80e75ddde065b0ed42aa530e8c40cb...,2025-01-01T00:00:00.000,2025-01-01T00:15:00.000,985.0,3.22,NaN,NaN,8.0,7.0,...,0.0,55.00,Cash,City Service,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),41.922686,-87.649489,POINT (-87.6494887289 41.9226862843)

In [ ]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Sample raw trip data                    #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

trip_sample = raw_trip_data.sample(frac=SAMPLE_FRAC, random_state=random_seed)

trip_sample.to_csv("data/samples/SAMPLE_CHICAGO_TAXI_TRIPS_2025.csv", index=False)

print(f"Sampled {len(trip_sample):,} rows ({SAMPLE_FRAC:.2%} of total)")
print(f"Saved to data/samples/SAMPLE_CHICAGO_TAXI_TRIPS_2025.csv")

Sampled 13,652 rows (0.20% of total)
Saved to data/samples/SAMPLE_CHICAGO_TAXI_TRIPS_2025.csv

## 0.2 Raw Chicago Weather Data

For the weather data, we decided to not sample both `data/weather/weather_daily.csv`and `data/weather/weather_hourly.csv` since these two datasets have sizes of 69KB and 1.9MB. Therefore the full datasets are no problem for exemplary compilation of code.

# 0.3 Cleaned Trip Data

Now we sample the **cleaned** taxi trip data.

The trip data cleaning can be found here: [Trip Data Cleaning](01_Preprocessing/01_03_Trip_Data_Cleanup.ipynb)

In [5]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Load cleaned trip data                  #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

cleaned_trip_data = pd.read_csv("data/trips/STATE_01_04_trip_data_cleanup_V1.csv")

cleaned_trip_data.head()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_census_tract,dropoff_census_tract,pickup_community_area,dropoff_community_area,...,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location
0,0275e2d8147a31e1ce320c5fb15f9910563cafe1,84957c8960b674346784746bbc1d48cafff4976b162323...,2025-01-01 00:00:00,2025-01-01 00:15:00,758.0,2.93,1.703108e+10,1.703108e+10,8.0,8.0,...,0.0,9.75,Prcard,Flash Cab,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),41.899602,-87.633308,POINT (-87.6333080367 41.899602111)
1,05aa05bf6f3ec476715fad9f706bd137e08e00b7,0cbf5c0f6aca3628d77c7b6fe89715757ed402a70b0f8b...,2025-01-01 00:00:00,2025-01-01 00:15:00,1233.0,13.66,1.703176e+10,1.703106e+10,76.0,6.0,...,5.0,48.60,Credit Card,Globe Taxi,41.980264,-87.913625,POINT (-87.913624596 41.9802643146),41.944227,-87.655998,POINT (-87.6559981815 41.9442266014)
2,17365c83264f028a307ac70308d770fe03bcbcae,c3f8e0b6712bf3ea80e75ddde065b0ed42aa530e8c40cb...,2025-01-01 00:00:00,2025-01-01 00:15:00,985.0,3.22,1.703108e+10,1.703107e+10,8.0,7.0,...,0.0,55.00,Cash,City Service,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),41.922686,-87.649489,POINT (-87.6494887289 41.9226862843)
3,1c629303d7f08492d97e13fabe6a0d1d81e6c9c5,c8f57a1150c210a9e6b3fcfb24c3d6d0a43d1879b4b979...,2025-01-01 00:00:00,2025-01-01 00:15:00,652.0,3.24,1.703122e+10,1.703107e+10,22.0,7.0,...,0.0,15.67,Mobile,Tac - Yellow Cab Association,41.922761,-87.699155,POINT (-87.6991553432 41.9227606205),41.922686,-87.649489,POINT (-87.6494887289 41.9226862843)
4,1cb48762978a475116ec833c0e4de8ed2ac88e14,88d8896a85cf755c4fb03711d495dc47ca8109196cdef6...,2025-01-01 00:00:00,2025-01-01 00:15:00,803.0,6.09,1.703108e+10,1.703103e+10,8.0,3.0,...,1.0,18.50,Cash,City Service,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),41.965812,-87.655879,POINT (-87.6558787862 41.96581197)

In [15]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Sample cleaned trip data                #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

trip_sample = cleaned_trip_data.sample(frac=SAMPLE_FRAC, random_state=random_seed)

trip_sample.to_csv("data/samples/SAMPLE_CHICAGO_TAXI_TRIPS_2025.csv", index=False)

print(f"Sampled {len(trip_sample):,} rows ({SAMPLE_FRAC:.2%} of total)")
print(f"Saved to data/samples/SAMPLE_cleaned_trips.csv")

Sampled 11,274 rows (0.20% of total)
Saved to data/samples/SAMPLE_cleaned_trips.csv

# 0.4 Merged Trip and Weather Data

After cleaning we merged the trip data with weather data.

The merging can be found in this notebook: [Trip Weather Data Merge](01_Preprocessing/01_05_Trips_Weather_Merge.ipynb)

In [12]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Load merged trip data                   #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

merged = pd.read_csv("data/merged/state_01_05_MERGED_TRIPS_WEATHER.csv")

In [16]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Sample merged data                      #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

trip_sample = merged.sample(frac=SAMPLE_FRAC, random_state=random_seed)

trip_sample.to_csv("data/samples/SAMPLE_CHICAGO_TAXI_TRIPS_2025.csv", index=False)

print(f"Sampled {len(trip_sample):,} rows ({SAMPLE_FRAC:.2%} of total)")
print(f"Saved to data/samples/SAMPLE_merged_trips_weather.csv")

Sampled 11,274 rows (0.20% of total)
Saved to data/samples/SAMPLE_merged_trips_weather.csv

# 0.4 Aggregated Data

Now we sample the aggregated trip and weather data.

The data aggregation can be found in this notebook: [Data Aggregation](01_Preprocessing/01_06_Data_Aggregation.ipynb)

In [ ]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Load aggregated data                    #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

demand_= pd.read_csv("data/aggregated/state_01_05_MERGED_TRIPS_WEATHER.csv")